[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
lib_deps = bblanchon/ArduinoJson@6.21.5
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
