#!/usr/bin/env python3
"""Validate disjoint job artifacts and generate the public download index/checksums."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]

def merge(build, firmware, output):
    b = json.loads((build/'build-manifest.json').read_text())
    f = json.loads((firmware/'firmware-manifest.json').read_text())
    if set(b['files']) & set(f['files']):
        raise ValueError('Build jobs supplied overlapping packages; publication stopped')
    expected_b = {b['android']['file'], b['windows']['file'], b['sdCopy']['file']}
    expected_f = {f['firmware']['sourceFile'], f['firmware']['binaryFile']}
    if set(b['files']) != expected_b or set(f['files']) != expected_f:
        raise ValueError('Missing or unexpected release packages')
    for directory, manifest in ((build,b), (firmware,f)):
        for name, checksum in manifest['files'].items():
            if Path(name).name != name or not name.endswith(('.apk','.zip')):
                raise ValueError('Invalid package name')
            path = directory/name
            if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != checksum:
                raise ValueError(f'Package integrity check failed: {name}')
    if b['android']['sha256'] != b['files'][b['android']['file']]:
        raise ValueError('Android manifest checksum mismatch')
    output.mkdir(parents=True, exist_ok=True)
    for directory, manifest in ((build,b), (firmware,f)):
        for name in manifest['files']:
            staging = output/(name+'.tmp')
            shutil.copyfile(directory/name, staging)
            staging.replace(output/name)
    manifest = {key:b[key] for key in ('android','windows','sdCopy')}
    manifest['firmware'] = f['firmware']
    (output/'release-manifest.json').write_text(json.dumps(manifest, indent=2)+'\n')
    android, windows, esp = b['android'], b['windows'], f['firmware']
    repository = os.environ.get('GITHUB_REPOSITORY', 'pugplayzYT/bluetooth-wide-web-bww-')
    raw = f'https://raw.githubusercontent.com/{repository}/main/downloads/'
    (output/'README.md').write_text(f'''# BWW downloads

This page is generated by GitHub Actions after both build jobs pass. Bookmark this page: the links below always point to the latest published packages. No tags are required. Older versioned files, if present, are historical downloads.

## Android app

[Download Android {android['version']}]({raw}{android['file']}) — Android 8 or newer. Allow notifications for background-upload status. Official releases use a private, stable signing key. See [signing and update compatibility](../ANDROID_SIGNING.md) before updating a legacy CI-signed installation.

## Windows server and Bluetooth sync

[Download Windows host/sync {windows['version']}]({raw}{windows['file']}) — extract and run Bww.Server.exe, or Sync-BWW.bat for reviewed website sync. No .NET installation required.

## ESP32 firmware

[Download precompiled firmware {esp['version']}]({raw}{esp['binaryFile']}) — includes the matching crash-decoder ELF and flashing instructions.

[Download PlatformIO sources {esp['version']}]({raw}{esp['sourceFile']}) — extract and open the esp32 folder. Requires an original ESP32 with Bluetooth Classic. Back up the SD card /bww folder before upgrading.

## SD-copy tool

[Download BWW SD Copy]({raw}{b['sdCopy']['file']}) — Python 3.10+, copies accounts and websites between PC and SD formats without formatting the card.

## Integrity

[SHA-256 checksums](SHA256SUMS.txt) cover every downloadable APK/ZIP in this directory. The official Android certificate SHA-256 is `{android['certificateSha256']}`. Private keys and passwords are never included in downloads. Android app fixes must increase versionName and versionCode; same-version code changes are rejected by packaging.
''')
    packages = sorted([*output.glob('*.zip'),*output.glob('*.apk')])
    (output/'SHA256SUMS.txt').write_text(''.join(f'{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}\n' for p in packages))
    print('Verified disjoint release packages and regenerated the latest-download index.')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--build', type=Path, default=ROOT/'artifacts/downloads-build')
    parser.add_argument('--firmware', type=Path, default=ROOT/'artifacts/downloads-firmware')
    parser.add_argument('--output', type=Path, default=ROOT/'downloads')
    args=parser.parse_args()
    merge(args.build,args.firmware,args.output)
