plugins { id 'com.android.application' }
android {
    namespace 'dev.bww'
    compileSdk 35
    buildToolsVersion '35.0.0'
    defaultConfig {
        applicationId 'dev.bww'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '0.5.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { release { minifyEnabled false } }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
}
